{
 "title": "Succinct Challenger",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Challenging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Challenger Activities",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(op_succinct_fp_challenger_games_challenged{job=\"challenger\"})",
     "legendFormat": "Challenged"
    },
    {
     "expr": "sum(op_succinct_fp_challenger_games_resolved{job=\"challenger\"})",
     "legendFormat": "Resolved"
    },
    {
     "expr": "sum(op_succinct_fp_challenger_games_bonds_claimed{job=\"challenger\"})",
     "legendFormat": "Bonds-claimed"
    }
   ]
  },
  {
   "title": "Challenger Activities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(op_succinct_fp_challenger_games_challenged{job=\"challenger\"})",
     "legendFormat": "Games challenged"
    },
    {
     "expr": "sum(op_succinct_fp_challenger_games_resolved{job=\"challenger\"})",
     "legendFormat": "Games resolved"
    },
    {
     "expr": "sum(op_succinct_fp_challenger_games_bonds_claimed{job=\"challenger\"})",
     "legendFormat": "Bonds claimed"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Challenger errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(op_succinct_fp_challenger_game_challenging_error)",
     "legendFormat": "Challenging errors"
    },
    {
     "expr": "sum(op_succinct_fp_challenger_game_resolution_error)",
     "legendFormat": "Resolution errors"
    },
    {
     "expr": "sum(op_succinct_fp_challenger_bond_claiming_error)",
     "legendFormat": "Bond-claiming errors"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(op_succinct_fp_challenger_game_challenging_error{job=\"challenger\"})",
     "legendFormat": "Challenging error"
    },
    {
     "expr": "sum(op_succinct_fp_challenger_bond_claiming_error{job=\"challenger\"})",
     "legendFormat": "Bond-claiming error"
    },
    {
     "expr": "sum(op_succinct_fp_challenger_game_resolution_error{job=\"challenger\"})",
     "legendFormat": "Resolution error"
    }
   ]
  }
 ]
}